apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuitemwebapplication-deployment
  labels:
    app: menuitemwebapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menuitemwebapplication
  template:
    metadata:
      labels:
        app: menuitemwebapplication
    spec:
      containers:
      - name: menuitemwebapplication
        image: menuitemcontainer.azurecr.io/menuitemserviceimage:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisecret
---
apiVersion: v1
kind: Service
metadata:
  name: menuitemwebappplicationsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: menuitemwebapplication