apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuitemwebapplication-deployment
  labels:
    app: MenuItemWebApplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MenuItemWebApplication 
  template:
    metadata:
      labels:
        app: MenuItemWebApplication
    spec:
      containers:
      - name: menuitemwebcontainer
        image: menuitemcontainer.azurecr.io/menuitemserviceiamge:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webiapisecret
---
apiVersion: v1
kind: Service
metadata:
  name: menuitemwebappplicationsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MenuItemWebApplication